### ISSUE TITLE
Implement the invitation email for NGO Admin and Specialist user

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/sunrise#222]
Email invitation template for NGO Admin: https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=7672-14011&t=tOp1b6oYTzb6Sgxw-4

Email invitation template for Specialist: https://www.figma.com/design/gpOGCkb9B6pTfe1DvleVMm/Sunrise?node-id=7672-14383&t=tOp1b6oYTzb6Sgxw-4

**Comment by alexPopaCode4** [comment]
De adaugat logo in email

**Comment by andrabrinzaniuc** [comment]
**POSSIBLE BUG:** For an Admin User, added in an organization with 2 tenants, they receive one email to configure their password as per the above ticket. They configure it, but they become active only in one tenant. A RESEND EMAIL is triggered for the inactive account. They receive the admin email a second time, they click on the link and they receive a 403 - Acest link a fost folosit deja. After they login again, they become active in the second tenant as well.

Expected behaviour - when an admin accepts an invite, they become active for ALL tenants of the selected institution

<img width="1153" alt="Image" src="https://github.com/user-attachments/assets/51e6893e-c800-4eb4-b6f3-b4a5043de67b" />
<img width="1336" alt="Image" src="https://github.com/user-attachments/assets/d1acc8ba-7b05-4e5b-997e-100b17399285" />
